### ISSUE TITLE
Seed Migration

### ISSUE THREAD

**Issue by gogolok** [DavidHuie/gomigrate#7]
I had multiple INSERT statements in an up file ('seed data').

```
INSERT INTO table1 (col1, col2) VALUES ("val1", "val2");
INSERT INTO table2 (col1) VALUES ("val1");
```

Since pull request #5 that migration is broken.
How I am supposed to correct this?

**Comment by DavidHuie** [comment]
@gogolok Could you provide more context? Which error is raised?

**Comment by DavidHuie** [comment]
Also, a minimal migration that reproduces the problem would be helpful.

**Comment by gogolok** [comment]
https://github.com/gogolok/gomigrate/compare/mysql_multiple_inserts

https://travis-ci.org/gogolok/gomigrate/builds/51486840

**Comment by DavidHuie** [comment]
@gogolok  unfortunately, there isn't a Go mysql driver that supports multiple statements. I used to have a hack that would split your SQL file by semicolons, but that obviously doesn't capture everything.

**Comment by ebonet** [comment]
I load my seed data from a csv file: LOAD DATA LOCAL INFILE 'seed.csv' INTO TABLE table CHARACTER SET 'utf8' FIELDS TERMINATED BY ',' IGNORE 1 LINES;

**Comment by gogolok** [comment]
Can be closed since current master supports multiple inserts.
